export const quotes = [
  {
    q: "Older men declare war. But it is youth that must fight and die.",
    a: "Herbert Hoover",
    c: "63",
    h: "<blockquote>&ldquo;Older men declare war. But it is youth that must fight and die.&rdquo; &mdash; <footer>Herbert Hoover</footer></blockquote>",
  },
  {
    q: "Remember the entrance to the sanctuary is inside you.",
    a: "Rumi",
    c: "53",
    h: "<blockquote>&ldquo;Remember the entrance to the sanctuary is inside you.&rdquo; &mdash; <footer>Rumi</footer></blockquote>",
  },
  {
    q: "It matters not who you love, where you love, why you love, when you love or how you love, it matters only that you love.",
    a: "John Lennon",
    c: "120",
    h: "<blockquote>&ldquo;It matters not who you love, where you love, why you love, when you love or how you love, it matters only that you love.&rdquo; &mdash; <footer>John Lennon</footer></blockquote>",
  },
  {
    q: "Change begets change. Nothing propagates so fast.",
    a: "Charles Dickens",
    c: "49",
    h: "<blockquote>&ldquo;Change begets change. Nothing propagates so fast.&rdquo; &mdash; <footer>Charles Dickens</footer></blockquote>",
  },
  {
    q: "Life is like a wheel. Sooner or later, it always comes around to where you started again.",
    a: "Stephen King",
    c: "89",
    h: "<blockquote>&ldquo;Life is like a wheel. Sooner or later, it always comes around to where you started again.&rdquo; &mdash; <footer>Stephen King</footer></blockquote>",
  },
  {
    q: "If you want to achieve greatness stop asking for permission.",
    a: "Unknown",
    c: "60",
    h: "<blockquote>&ldquo;If you want to achieve greatness stop asking for permission.&rdquo; &mdash; <footer>Unknown</footer></blockquote>",
  },
  {
    q: "We would accomplish many more things if we did not think of them as impossible.",
    a: "Vince Lombardi",
    c: "79",
    h: "<blockquote>&ldquo;We would accomplish many more things if we did not think of them as impossible.&rdquo; &mdash; <footer>Vince Lombardi</footer></blockquote>",
  },
  {
    q: "Normality is a paved road: It's comfortable to walk, but no flowers grow on it.",
    a: "Vincent van Gogh",
    c: "79",
    h: "<blockquote>&ldquo;Normality is a paved road: It's comfortable to walk, but no flowers grow on it.&rdquo; &mdash; <footer>Vincent van Gogh</footer></blockquote>",
  },
  {
    q: "Once you learn to quit, it becomes a habit.",
    a: "Vince Lombardi",
    c: "43",
    h: "<blockquote>&ldquo;Once you learn to quit, it becomes a habit.&rdquo; &mdash; <footer>Vince Lombardi</footer></blockquote>",
  },
  {
    q: "Human beings believe just as they breathe - in order to survive.",
    a: "Carlos Ruiz Zafon",
    c: "64",
    h: "<blockquote>&ldquo;Human beings believe just as they breathe - in order to survive.&rdquo; &mdash; <footer>Carlos Ruiz Zafon</footer></blockquote>",
  },
  {
    q: "If I can laugh, I can live.",
    a: "Christopher Reeve",
    c: "27",
    h: "<blockquote>&ldquo;If I can laugh, I can live.&rdquo; &mdash; <footer>Christopher Reeve</footer></blockquote>",
  },
  {
    q: "When uncomfortable, my instinct is not to avoid the discomfort but to become at peace with it.",
    a: "Josh Waitzkin",
    c: "94",
    h: "<blockquote>&ldquo;When uncomfortable, my instinct is not to avoid the discomfort but to become at peace with it.&rdquo; &mdash; <footer>Josh Waitzkin</footer></blockquote>",
  },
  {
    q: "Doing the best at this moment puts you in the best place for the next moment.",
    a: "Oprah Winfrey",
    c: "77",
    h: "<blockquote>&ldquo;Doing the best at this moment puts you in the best place for the next moment.&rdquo; &mdash; <footer>Oprah Winfrey</footer></blockquote>",
  },
  {
    q: "Many a man has failed because he had his wishbone where his backbone should have been.",
    a: "Ronald Reagan",
    c: "86",
    h: "<blockquote>&ldquo;Many a man has failed because he had his wishbone where his backbone should have been.&rdquo; &mdash; <footer>Ronald Reagan</footer></blockquote>",
  },
  {
    q: "We must have strong minds, ready to accept facts as they are.",
    a: "Harry S. Truman",
    c: "61",
    h: "<blockquote>&ldquo;We must have strong minds, ready to accept facts as they are.&rdquo; &mdash; <footer>Harry S. Truman</footer></blockquote>",
  },
  {
    q: "True it is, we only hate those whom we do not know.",
    a: "Andrew Carnegie",
    c: "51",
    h: "<blockquote>&ldquo;True it is, we only hate those whom we do not know.&rdquo; &mdash; <footer>Andrew Carnegie</footer></blockquote>",
  },
  {
    q: "If you see someone without a smile give them one of yours.",
    a: "Unknown",
    c: "58",
    h: "<blockquote>&ldquo;If you see someone without a smile give them one of yours.&rdquo; &mdash; <footer>Unknown</footer></blockquote>",
  },
  {
    q: "Help others achieve their dreams and you will achieve yours.",
    a: "Les Brown",
    c: "60",
    h: "<blockquote>&ldquo;Help others achieve their dreams and you will achieve yours.&rdquo; &mdash; <footer>Les Brown</footer></blockquote>",
  },
  {
    q: "You were put on this earth to achieve your greatest self, to live out your purpose, and to do it courageously.",
    a: "Steve Maraboli",
    c: "110",
    h: "<blockquote>&ldquo;You were put on this earth to achieve your greatest self, to live out your purpose, and to do it courageously.&rdquo; &mdash; <footer>Steve Maraboli</footer></blockquote>",
  },
  {
    q: "Listen to what you know instead of what you fear.",
    a: "Richard Bach",
    c: "49",
    h: "<blockquote>&ldquo;Listen to what you know instead of what you fear.&rdquo; &mdash; <footer>Richard Bach</footer></blockquote>",
  },
  {
    q: "Be brave to stand for what you believe in even if you stand alone.",
    a: "Roy T. Bennett",
    c: "66",
    h: "<blockquote>&ldquo;Be brave to stand for what you believe in even if you stand alone.&rdquo; &mdash; <footer>Roy T. Bennett</footer></blockquote>",
  },
  {
    q: "Where there's life, there's hope.",
    a: "Stephen Hawking",
    c: "33",
    h: "<blockquote>&ldquo;Where there's life, there's hope.&rdquo; &mdash; <footer>Stephen Hawking</footer></blockquote>",
  },
  {
    q: "Longevity is a fleeting moment that lasts forever.",
    a: "Vidal Sassoon",
    c: "50",
    h: "<blockquote>&ldquo;Longevity is a fleeting moment that lasts forever.&rdquo; &mdash; <footer>Vidal Sassoon</footer></blockquote>",
  },
  {
    q: "Be content with what you have, rejoice in the way things are. When you realize there is nothing lacking, the whole world belongs to you.",
    a: "Lao Tzu",
    c: "136",
    h: "<blockquote>&ldquo;Be content with what you have, rejoice in the way things are. When you realize there is nothing lacking, the whole world belongs to you.&rdquo; &mdash; <footer>Lao Tzu</footer></blockquote>",
  },
  {
    q: "Leave the beaten track behind occasionally and dive into the woods. Every time you do you will be certain to find something you have never seen before.",
    a: "Alexander Graham Bell",
    c: "151",
    h: "<blockquote>&ldquo;Leave the beaten track behind occasionally and dive into the woods. Every time you do you will be certain to find something you have never seen before.&rdquo; &mdash; <footer>Alexander Graham Bell</footer></blockquote>",
  },
  {
    q: "The sweetest pleasure arises from difficulties overcome.",
    a: "Publilius Syrus",
    c: "56",
    h: "<blockquote>&ldquo;The sweetest pleasure arises from difficulties overcome.&rdquo; &mdash; <footer>Publilius Syrus</footer></blockquote>",
  },
  {
    q: "How people treat you is their karma; how you react is yours. ",
    a: "Wayne Dyer",
    c: "61",
    h: "<blockquote>&ldquo;How people treat you is their karma; how you react is yours. &rdquo; &mdash; <footer>Wayne Dyer</footer></blockquote>",
  },
  {
    q: "Look to the beauty of this day, miracles are all around you.",
    a: "Mary Engelbreit",
    c: "60",
    h: "<blockquote>&ldquo;Look to the beauty of this day, miracles are all around you.&rdquo; &mdash; <footer>Mary Engelbreit</footer></blockquote>",
  },
  {
    q: "Wherever you are, and whatever you do, be in love.",
    a: "Rumi",
    c: "50",
    h: "<blockquote>&ldquo;Wherever you are, and whatever you do, be in love.&rdquo; &mdash; <footer>Rumi</footer></blockquote>",
  },
  {
    q: "Ancient Rule of Twenty-one: if you do anything for twenty-one days in a row, it will be installed as a habit.",
    a: "Robin Sharma",
    c: "109",
    h: "<blockquote>&ldquo;Ancient Rule of Twenty-one: if you do anything for twenty-one days in a row, it will be installed as a habit.&rdquo; &mdash; <footer>Robin Sharma</footer></blockquote>",
  },
  {
    q: "Nothing is more creative...nor destructive...than a brilliant mind with a purpose.",
    a: "Dan Brown",
    c: "82",
    h: "<blockquote>&ldquo;Nothing is more creative...nor destructive...than a brilliant mind with a purpose.&rdquo; &mdash; <footer>Dan Brown</footer></blockquote>",
  },
  {
    q: "You can avoid reality, but you cannot avoid the consequences of avoiding reality.",
    a: "Ayn Rand",
    c: "81",
    h: "<blockquote>&ldquo;You can avoid reality, but you cannot avoid the consequences of avoiding reality.&rdquo; &mdash; <footer>Ayn Rand</footer></blockquote>",
  },
  {
    q: "You use a glass mirror to see your face; you use works of art to see your soul.",
    a: "George Bernard Shaw",
    c: "79",
    h: "<blockquote>&ldquo;You use a glass mirror to see your face; you use works of art to see your soul.&rdquo; &mdash; <footer>George Bernard Shaw</footer></blockquote>",
  },
  {
    q: "It's easy to be a critic, but being a doer requires effort, risk, and change.  ",
    a: "Wayne Dyer",
    c: "79",
    h: "<blockquote>&ldquo;It's easy to be a critic, but being a doer requires effort, risk, and change.  &rdquo; &mdash; <footer>Wayne Dyer</footer></blockquote>",
  },
  {
    q: "People who belittle people, will be LITTLE people, and will accomplish very Little",
    a: "Norman Vincent Peale",
    c: "82",
    h: "<blockquote>&ldquo;People who belittle people, will be LITTLE people, and will accomplish very Little&rdquo; &mdash; <footer>Norman Vincent Peale</footer></blockquote>",
  },
  {
    q: "Success is doing what you want to do, when you want, where you want, with whom you want, as much as you want.",
    a: "Tony Robbins",
    c: "109",
    h: "<blockquote>&ldquo;Success is doing what you want to do, when you want, where you want, with whom you want, as much as you want.&rdquo; &mdash; <footer>Tony Robbins</footer></blockquote>",
  },
  {
    q: "Every moment you get is a gift. Spend it on things that matter. Don't spend it by dwelling on unhappy things.",
    a: "Celestine Chua",
    c: "109",
    h: "<blockquote>&ldquo;Every moment you get is a gift. Spend it on things that matter. Don't spend it by dwelling on unhappy things.&rdquo; &mdash; <footer>Celestine Chua</footer></blockquote>",
  },
  {
    q: "The scariest moment is always just before you start. After that, things can only get better.",
    a: "Stephen King",
    c: "92",
    h: "<blockquote>&ldquo;The scariest moment is always just before you start. After that, things can only get better.&rdquo; &mdash; <footer>Stephen King</footer></blockquote>",
  },
  {
    q: "We are always complaining that our days are few, and acting as though there would be no end of them.  ",
    a: "Seneca",
    c: "102",
    h: "<blockquote>&ldquo;We are always complaining that our days are few, and acting as though there would be no end of them.  &rdquo; &mdash; <footer>Seneca</footer></blockquote>",
  },
  {
    q: "I can live without money, but I cannot live without love.",
    a: "Judy Garland",
    c: "57",
    h: "<blockquote>&ldquo;I can live without money, but I cannot live without love.&rdquo; &mdash; <footer>Judy Garland</footer></blockquote>",
  },
  {
    q: "Trust is the foundation of great leadership.",
    a: "Lolly Daskal",
    c: "44",
    h: "<blockquote>&ldquo;Trust is the foundation of great leadership.&rdquo; &mdash; <footer>Lolly Daskal</footer></blockquote>",
  },
  {
    q: "Muddy water is best cleared by leaving it alone.",
    a: "Alan Watts",
    c: "48",
    h: "<blockquote>&ldquo;Muddy water is best cleared by leaving it alone.&rdquo; &mdash; <footer>Alan Watts</footer></blockquote>",
  },
  {
    q: "Don't let the behavior of others destroy your inner peace.",
    a: "Dalai Lama",
    c: "58",
    h: "<blockquote>&ldquo;Don't let the behavior of others destroy your inner peace.&rdquo; &mdash; <footer>Dalai Lama</footer></blockquote>",
  },
  {
    q: "The only difference between success and failure is the ability to take action.",
    a: "Alexander Graham Bell",
    c: "78",
    h: "<blockquote>&ldquo;The only difference between success and failure is the ability to take action.&rdquo; &mdash; <footer>Alexander Graham Bell</footer></blockquote>",
  },
  {
    q: "As you think, you travel, and as you love, you attract.",
    a: "James Allen",
    c: "55",
    h: "<blockquote>&ldquo;As you think, you travel, and as you love, you attract.&rdquo; &mdash; <footer>James Allen</footer></blockquote>",
  },
  {
    q: "Your mind will make you rich or poor, depending on the use you put to it.",
    a: "Brian Tracy",
    c: "73",
    h: "<blockquote>&ldquo;Your mind will make you rich or poor, depending on the use you put to it.&rdquo; &mdash; <footer>Brian Tracy</footer></blockquote>",
  },
  {
    q: "The primary point of this existence is to live, and all living things move and grow.",
    a: "Ming-Dao Deng",
    c: "84",
    h: "<blockquote>&ldquo;The primary point of this existence is to live, and all living things move and grow.&rdquo; &mdash; <footer>Ming-Dao Deng</footer></blockquote>",
  },
  {
    q: "To be fully alive is to feel that everything is possible.",
    a: "Eric Hoffer",
    c: "57",
    h: "<blockquote>&ldquo;To be fully alive is to feel that everything is possible.&rdquo; &mdash; <footer>Eric Hoffer</footer></blockquote>",
  },
  {
    q: "The key to success is action.",
    a: "Brian Tracy",
    c: "29",
    h: "<blockquote>&ldquo;The key to success is action.&rdquo; &mdash; <footer>Brian Tracy</footer></blockquote>",
  },
  {
    q: "Although the world is full of suffering, it is also full of the overcoming of it.",
    a: "Helen Keller",
    c: "81",
    h: "<blockquote>&ldquo;Although the world is full of suffering, it is also full of the overcoming of it.&rdquo; &mdash; <footer>Helen Keller</footer></blockquote>",
  },
];
